const form=document.getElementById('authForm'),authView=document.getElementById('authView'),dashboard=document.getElementById('dashboardView'),error=document.getElementById('errorMessage');let createMode=false,loginRole='student';
const verifyView=document.getElementById('verifyView'),resetView=document.getElementById('resetView');let pendingAccount=null,signupOtp='',resetOtpCode='',resetRequested=false;
const makeOtp=()=>String(Math.floor(100000+Math.random()*900000));
function showAuth(){verifyView.hidden=true;resetView.hidden=true;dashboard.hidden=true;authView.hidden=false;}
function showVerification(user){pendingAccount=user;signupOtp=makeOtp();authView.hidden=true;verifyView.hidden=false;document.getElementById('verifyEmail').textContent=user.email;document.getElementById('verifyOtpHint').textContent='A 6-digit OTP has been sent to your email address. Check your inbox and spam folder.';}
const account=()=>JSON.parse(localStorage.getItem('launchpadAccount')||'null');
const students=()=>JSON.parse(localStorage.getItem('tksctStudents')||'[]');
const saveStudents=list=>localStorage.setItem('tksctStudents',JSON.stringify(list));
const escapeText=value=>String(value).replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
function renderStudents(){const list=students(),container=document.getElementById('studentList');container.innerHTML=list.length?list.map(student=>`<article class="student-item"><div><strong>${escapeText(student.name)}</strong><small>${escapeText(student.email)} · ${escapeText(student.semester)}</small></div><button type="button" class="edit-student" data-student-id="${student.id}">Modify</button><button type="button" class="delete-student" data-student-id="${student.id}">Delete</button></article>`).join(''):'<p class="record-note">No students added yet.</p>';}
const defaultRecords={dataStructures:{attendance:92,mark:null},databaseManagement:{attendance:88,mark:null},computerNetworks:{attendance:76,mark:null},mathematics:{attendance:84,mark:null}};
const records=()=>JSON.parse(localStorage.getItem('campusRecords')||JSON.stringify(defaultRecords));
function updateRecordDisplay(){const data=records(),values=Object.values(data);Object.entries(data).forEach(([subject,record])=>{document.getElementById(`${subject}Bar`).style.width=`${record.attendance}%`;document.getElementById(`${subject}Attendance`).textContent=`${record.attendance}%`;});const attendance=Math.round(values.reduce((sum,item)=>sum+item.attendance,0)/values.length),marks=values.filter(item=>item.mark!==null);document.getElementById('overallAttendance').textContent=`${attendance}%`;document.getElementById('classesAttended').textContent=`${Math.round(attendance/2)}/50`;document.getElementById('averageMark').textContent=marks.length?`${Math.round(marks.reduce((sum,item)=>sum+item.mark,0)/marks.length)}%`:'--';}
function showDashboard(user){authView.hidden=true;verifyView.hidden=true;resetView.hidden=true;dashboard.hidden=false;const first=user.name.trim().split(' ')[0],isStaff=user.role==='staff';dashboard.classList.toggle('staff-mode',isStaff);document.getElementById('welcomeTitle').textContent=`Good morning, ${first}.`;document.getElementById('profileInitial').textContent=first.charAt(0).toUpperCase();document.getElementById('dashboardKicker').textContent=isStaff?'STAFF DASHBOARD':'STUDENT DASHBOARD';document.getElementById('dashboardSubtitle').textContent=isStaff?'Manage attendance, marks, subjects and semester records.':'View your attendance and academic marks for this semester.';updateRecordDisplay();if(isStaff)renderStudents();}
function setMode(create){createMode=create;authView.classList.toggle('create-mode',create);error.textContent='';document.getElementById('formKicker').textContent=create?'STUDENT REGISTRATION':'STUDENT LOGIN';document.getElementById('formTitle').textContent=create?'Create your student account':'Welcome back, student';document.getElementById('formSubtitle').textContent=create?'Register to access your college portal.':'Sign in to view your academic dashboard.';document.getElementById('submitButton').innerHTML=`${create?'Create account':'Sign in'} <span>→</span>`;document.getElementById('switchText').innerHTML=create?'Already registered? <button type="button" class="text-link switch-mode">Sign in</button>':'New student? <button type="button" class="text-link switch-mode">Create an account</button>';document.getElementById('password').autocomplete=create?'new-password':'current-password';if(!create)setLoginRole(loginRole);}
function setLoginRole(role){loginRole=role;document.querySelectorAll('.login-tab').forEach(button=>button.classList.toggle('active',button.dataset.loginRole===role));document.getElementById('formKicker').textContent=`${role.toUpperCase()} LOGIN`;document.getElementById('formTitle').textContent=`Welcome back, ${role}.`;document.getElementById('formSubtitle').textContent=role==='staff'?'Sign in to manage academic records.':'Sign in to view your academic dashboard.';document.getElementById('switchText').innerHTML=role==='staff'?'New staff member? <button type="button" class="text-link switch-mode">Create an account</button>':'New student? <button type="button" class="text-link switch-mode">Create an account</button>';}
document.addEventListener('click',e=>{if(e.target.closest('.switch-mode'))setMode(!createMode)});
document.querySelectorAll('.login-tab').forEach(button=>button.addEventListener('click',()=>setLoginRole(button.dataset.loginRole)));
document.querySelector('.show-password').addEventListener('click',e=>{const p=document.getElementById('password'),visible=p.type==='text';p.type=visible?'password':'text';e.currentTarget.textContent=visible?'Show':'Hide';});
form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';const name=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value,role=document.getElementById('role').value;if(!email||!password)return error.textContent='Please enter your email and password.';if(createMode){if(!name)return error.textContent='Please tell us your name.';if(password.length<6)return error.textContent='Your password needs at least 6 characters.';if(!document.getElementById('terms').checked)return error.textContent='Please accept the terms to continue.';const saved=account();if(saved&&saved.email===email)return error.textContent='An account already exists for this email or register number. Please sign in.';showVerification({name,email,password,role});}else{const saved=account();if(!saved)return error.textContent='No account found. Create one to get started.';const savedRole=saved.role||'student';if(saved.email!==email||saved.password!==password)return error.textContent='That email or password does not match.';if(savedRole!==loginRole)return error.textContent=`This is a ${savedRole} account. Please use ${savedRole} login.`;showDashboard({...saved,role:savedRole});}});
document.getElementById('logoutButton').addEventListener('click',()=>{dashboard.hidden=true;authView.hidden=false;form.reset();setMode(false)});
document.getElementById('recordForm').addEventListener('submit',e=>{e.preventDefault();const subject=document.getElementById('subjectSelect').value,attendance=Number(document.getElementById('attendanceInput').value),mark=Number(document.getElementById('marksInput').value),message=document.getElementById('recordMessage');if(attendance<0||attendance>100||mark<0||mark>100){message.textContent='Attendance and marks must be between 0 and 100.';return;}const data=records();data[subject]={attendance,mark};localStorage.setItem('campusRecords',JSON.stringify(data));updateRecordDisplay();message.textContent='Academic record saved successfully.';e.currentTarget.reset();});
function markToday(present){const subject=document.getElementById('subjectSelect').value,data=records(),record=data[subject];record.attendance=Math.max(0,Math.min(100,record.attendance+(present?1:-1)));localStorage.setItem('campusRecords',JSON.stringify(data));updateRecordDisplay();document.getElementById('recordMessage').textContent=`${present?'Present':'Absent'} marked for today. ${record.attendance}% attendance recorded for this subject.`;}
document.getElementById('presentButton').addEventListener('click',()=>markToday(true));
document.getElementById('absentButton').addEventListener('click',()=>markToday(false));
document.getElementById('verifyForm').addEventListener('submit',e=>{e.preventDefault();const entered=document.getElementById('verifyOtp').value.trim(),message=document.getElementById('verifyError');if(entered!==signupOtp)return message.textContent='The OTP is incorrect. Please try again.';localStorage.setItem('launchpadAccount',JSON.stringify(pendingAccount));showDashboard(pendingAccount);pendingAccount=null;});
document.getElementById('forgotLink').addEventListener('click',()=>{authView.hidden=true;resetView.hidden=false;resetRequested=false;document.querySelector('.reset-code-fields').hidden=true;document.getElementById('resetButton').textContent='Send OTP';document.getElementById('resetError').textContent='';document.getElementById('resetForm').reset();});
document.getElementById('resetForm').addEventListener('submit',e=>{e.preventDefault();const saved=account(),email=document.getElementById('resetEmail').value.trim().toLowerCase(),message=document.getElementById('resetError');message.textContent='';if(!resetRequested){if(!saved||saved.email!==email)return message.textContent='No account was found with this email or register number.';resetOtpCode=makeOtp();resetRequested=true;document.querySelector('.reset-code-fields').hidden=false;document.getElementById('resetOtpHint').textContent='A 6-digit OTP has been sent to your email address. Check your inbox and spam folder.';document.getElementById('resetTitle').textContent='Verify your email';document.getElementById('resetSubtitle').textContent='Enter the OTP and choose a new password.';document.getElementById('resetButton').textContent='Reset password';return;}const otp=document.getElementById('resetOtp').value.trim(),newPassword=document.getElementById('newPassword').value;if(otp!==resetOtpCode)return message.textContent='The OTP is incorrect. Please try again.';if(newPassword.length<6)return message.textContent='Your password needs at least 6 characters.';localStorage.setItem('launchpadAccount',JSON.stringify({...saved,password:newPassword}));showAuth();form.reset();setMode(false);error.textContent='Password updated. Please sign in.';});
document.querySelectorAll('[data-back="auth"]').forEach(button=>button.addEventListener('click',()=>{showAuth();setMode(false);}));
document.getElementById('studentForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('studentName').value.trim(),email=document.getElementById('studentEmail').value.trim(),semester=document.getElementById('studentSemester').value,id=document.getElementById('editStudentId').value,message=document.getElementById('studentMessage');if(!name||!email)return message.textContent='Enter the student name and email or register number.';const list=students();if(id){const student=list.find(item=>item.id===id);Object.assign(student,{name,email,semester});message.textContent='Student details updated successfully.';}else{list.push({id:String(Date.now()),name,email,semester});message.textContent='Student added successfully.';}saveStudents(list);e.currentTarget.reset();document.getElementById('editStudentId').value='';document.getElementById('studentSaveButton').textContent='Add student';renderStudents();});
document.getElementById('studentList').addEventListener('click',e=>{const id=e.target.dataset.studentId;if(!id)return;const list=students(),student=list.find(item=>item.id===id);if(e.target.classList.contains('delete-student')){saveStudents(list.filter(item=>item.id!==id));document.getElementById('studentMessage').textContent='Student deleted successfully.';renderStudents();}if(e.target.classList.contains('edit-student')&&student){document.getElementById('studentName').value=student.name;document.getElementById('studentEmail').value=student.email;document.getElementById('studentSemester').value=student.semester;document.getElementById('editStudentId').value=id;document.getElementById('studentSaveButton').textContent='Save changes';document.getElementById('studentMessage').textContent='Edit the student details, then save changes.';}});
